name: Build RHEL10 bootc image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to RHCR
        uses: docker/login-action@v4
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_REGISTRY_USERNAME }}
          password: ${{ secrets.REDHAT_REGISTRY_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/rhel10-bootc-swarm
          tags: |
            type=raw,value=latest

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
